config/routes.rb
Bookish::Application.routes.draw do
  resources :authors


  resources :users


  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  resources :users
  resources :sessions
  resources :books

  root to: "books#index"
end

app/models/author.rb
class Author < ActiveRecord::Base
  attr_accessible :born, :died, :name, :nationality

  has_many :authorships
  has_many :books, through: :authorships, uniq: true
end

app/models/authorship.rb
class Authorship < ActiveRecord::Base
  attr_accessible :author_id, :book_id

  belongs_to :author
  belongs_to :book
end

app/models/book.rb
class Book < ActiveRecord::Base
  attr_accessible :description, :isbn, :lang, :page_count, :published_by, :published_in, :title, :author

  attr_accessor :author

  has_many :authorships, dependent: :destroy
  has_many :authors, through: :authorships, uniq: true

  before_save do
    old_author = self.authors.first
    new_author = Author.find(author)
    if old_author != new_author
      self.authors = [new_author]
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  attr_accessible :email, :password, :password_confirmation, :name, :address

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email

  def admin?
    false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :admin?

  def admin?
    current_user && current_user.admin?
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @authors }
    end
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
    @author = Author.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @author }
    end
  end

  # GET /authors/new
  # GET /authors/new.json
  def new
    @author = Author.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @author }
    end
  end

  # GET /authors/1/edit
  def edit
    @author = Author.find(params[:id])
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(params[:author])

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render json: @author, status: :created, location: @author }
      else
        format.html { render action: "new" }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /authors/1
  # PUT /authors/1.json
  def update
    @author = Author.find(params[:id])

    respond_to do |format|
      if @author.update_attributes(params[:author])
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author = Author.find(params[:id])
    @author.destroy

    respond_to do |format|
      format.html { redirect_to authors_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  # GET /books
  # GET /books.json
  def index
    if params[:view].present? && session[:book_view] != params[:view]
      session[:book_view] = params[:view]
    end
    @books = Book.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @books }
    end
  end

  # GET /books/1
  # GET /books/1.json
  def show
    @book = Book.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @book }
    end
  end

  # GET /books/new
  # GET /books/new.json
  def new
    @book = Book.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @book }
    end
  end

  # GET /books/1/edit
  def edit
    @book = Book.find(params[:id])
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(params[:book])

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render json: @book, status: :created, location: @book }
      else
        format.html { render action: "new" }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /books/1
  # PUT /books/1.json
  def update
    @book = Book.find(params[:id])

    respond_to do |format|
      if @book.update_attributes(params[:book])
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book = Book.find(params[:id])
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = login(params[:email], params[:password], params[:remember_me])
    if user
      redirect_back_or_to root_url, :notice => "Logged in!"
    else
      flash.now.alert = "Email or password was invalid."
      render :new
    end
  end

  def destroy
    logout
    redirect_to root_url, :notice => "Logged out!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to root_url, :notice => "Signed up!"
    else
      render :new
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/authors/_form.html.erb
<%= form_for @author, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :nationality, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :nationality, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :born, :class => 'control-label' %>
    <div class="controls">
      <%= f.date_select :born, :class => 'date_select', use_short_month: true, start_year: 1900, include_blank: true %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :died, :class => 'control-label' %>
    <div class="controls">
      <%= f.date_select :died, :class => 'date_select', use_short_month: true, start_year: 1900, include_blank: true %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                authors_path, :class => 'btn' %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<%- model_class = Author -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/authors/index.html.erb
<%- model_class = Author -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:nationality) %></th>
      <th><%= model_class.human_attribute_name(:born) %></th>
      <th><%= model_class.human_attribute_name(:died) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= author.name %></td>
        <td><%= author.nationality %></td>
        <td><%= author.born %></td>
        <td><%= author.died %></td>
        <td>
          <%= link_to t('.profile', :default => 'Show'),
                      author_path(author), :class => 'btn btn-mini btn-info' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_author_path(author), :class => 'btn btn-mini' %>
          <% if admin? %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      author_path(author),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_author_path,
            :class => 'btn btn-primary' %>

app/views/authors/new.html.erb
<%- model_class = Author -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/authors/show.html.erb
<%- model_class = Author -%>
<div class="page-header">
  <h1><%= @author.name %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:nationality) %>:</strong></dt>
  <dd><%= @author.nationality %></dd>
  <dt><strong><%= model_class.human_attribute_name(:born) %>:</strong></dt>
  <dd><%= @author.born %></dd>
  <dt><strong><%= model_class.human_attribute_name(:died) %>:</strong></dt>
  <dd><%= @author.died %></dd>
</dl>

<div class='row-fluid'>
  <div class='span6' style='padding: 10px; border: 1px solid #f1f1f1'>
    <h2>Books</h2>
      <% @author.books.each do |book| %>
        <a href="<%= book_path(book) %>" class="span2 user-book" style="text-align: center">
          <%= image_tag "/covers/#{book.isbn}.jpg", size: '71x107', class: "cover" %>
          <br />
            <%= book.title %>
        </a>
      <% end %>
  </div>
  <div class='span6' style='padding: 10px; border: 1px solid #f1f1f1'>
    <h2>Quotes</h2>
  </div>
</div>
<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              authors_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_author_path(@author), :class => 'btn' %>
  <% if admin? %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              author_path(@author),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
  <% end %>
</div>

app/views/books/_form.html.erb
<%= form_for @book, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'text_field span10' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :author, :class => 'control-label' %>
    <div class="controls">
      <%= f.select :author, Author.all.map{ |a| [a.name, a.id] }, :class => 'text_field span10' %>
      &nbsp;
      <%= link_to 'Add', new_author_path, target: '_blank' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :description, rows: 5, :class => 'text_field span10' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :isbn, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :isbn, :class => 'text_field span10' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :lang, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :lang, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :published_in, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :published_in, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :published_by, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :published_by, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                books_path, :class => 'btn' %>
  </div>
<% end %>

app/views/books/_library_view.html.erb
<div class="row-fluid">
  <div class="span-11">
    <% @books.each do |book| %>
      <a href="<%= book_path(book) %>" class="span2 library-book" style="text-align: center">
        <%= image_tag "/covers/#{book.isbn}.jpg", size: '146x226', class: "cover" %>
        <br />
          <%= book.title %>
      </a>
    <% end %>
  </div>
</div>

app/views/books/_table_view.html.erb
<%- model_class = Book -%>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:isbn) %></th>
      <th><%= model_class.human_attribute_name(:published_in) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= truncate book.description %></td>
        <td><%= book.isbn %></td>
        <td><%= book.published_in %></td>
        <td>
          <%= link_to t('.profile', :default => 'Show'),
                      book_path(book), :class => 'btn btn-mini btn-info' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_book_path(book), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      book_path(book),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<%- model_class = Book -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/books/index.html.erb
<%- model_class = Book -%>
<div class="page-header">
  <h1 class="span11"><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
  <div class="span1 submenu" style="font-size: 18px">
    <a href="<%= books_path(view: 'list') %>">
      <i class="icon-th-list"></i>
    </a>
    &nbsp;
    <a href="<%= books_path(view: 'lib') %>">
      <i class="icon-th"></i>
    </a>
  </div>
</div>
<% if session[:book_view] == 'lib' %>
  <%= render :partial => 'books/library_view' %>
<% else %>
  <%= render :partial => 'books/table_view' %>
<% end %>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_book_path,
            :class => 'btn btn-primary' %>

app/views/books/new.html.erb
<%- model_class = Book -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/books/show.html.erb
<%- model_class = Book -%>
<div class='page-header'>
  <h1><%= @book.title %></h1>
  <span class='author'>
    by <%= link_to @book.authors.first.name, author_path(@book.authors.first) %>
  </span>
</div>
<div class="row-fluid">
  <div class="span2">
    <%= image_tag "/covers/#{@book.isbn}.jpg", size: '146x226' %>
      <a class="btn btn-success btn-small span" style="margin-top: 10px;" href="#">Want</a>
      <a class="btn btn-warning btn-small span" style="margin-top: 5px" href="#">Have</a>
  </div>
  <div class="span9">
        <p>
          <%= @book.description %>
        </p>
    <dl class="dl-horizontal">
      <dt><strong><%= model_class.human_attribute_name(:isbn) %>:</strong></dt>
      <dd><%= @book.isbn %></dd>
      <dt><strong><%= model_class.human_attribute_name(:lang) %>:</strong></dt>
      <dd><%= @book.lang %></dd>
      <dt><strong><%= model_class.human_attribute_name(:published_in) %>:</strong></dt>
      <dd><%= @book.published_in %></dd>
      <dt><strong><%= model_class.human_attribute_name(:published_by) %>:</strong></dt>
      <dd><%= @book.published_by %></dd>
    </dl>
        
  </div>
  <div class="span11">
    <div class="form-actions">
      <%= link_to t('.back', :default => t("helpers.links.back")),
                  books_path, :class => 'btn'  %>
      <%= link_to t('.edit', :default => t("helpers.links.edit")),
                  edit_book_path(@book), :class => 'btn' %>
    <% if admin? %>
      <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                  book_path(@book),
                  :method => 'delete',
                  :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                  :class => 'btn btn-danger' %>
      <% end %>
    </div>
  </div>

  
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Bookish" %></title>
    <%= csrf_meta_tags %>


    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>
    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Bookish</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#" >
                  Books
                  <b class="caret"></b></b>
                </a>
                <ul id="swatch-menu" class="dropdown-menu">
                  <li>
                    <a href="<%= books_path %>">
                      <i class="icon-list icon-white"></i>
                        Browse
                    </a>
                  </li>
                  <li>
                    <a href="<%= new_book_path %>">
                      <i class="icon-upload icon-white"></i>
                        Import
                    </a>
                  </li>
                </ul>
                <li><%= link_to "Users", "/users"  %></li>
                </ul>
              </li>
            <ul class="nav pull-right">
              <% if current_user %>
                <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#" >
                  <i class="icon-user icon-white"></i>
                  <%= current_user.email %>
                  <b class="caret"></b></b>
                </a>
                <ul id="swatch-menu" class="dropdown-menu">
                  <li>
                    <a href="<%= root_path %>">
                      <i class="icon-home icon-white"></i>
                      Home
                    </a>
                  </li>
                  <li>
                    <a href="<%= user_path(current_user) %>">
                      <i class="icon-wrench icon-white"></i>
                      Profile
                    </a>
                  </li>
                  <li>
                    <a href="#">
                      <i class="icon-th-list icon-white"></i>
                      History
                    </a>
                  </li>
                  <li class="divider"></li>
                  <li>
                    <a href="<%= logout_path %>">
                      <i class="icon-off icon-white"></i>
                      Logout
                    </a>
                  </li>
                </ul>
                </li>
              <% else %>
                <li>
                  <%= link_to "Sign up", signup_path %>
                </li>
                <li>
                  <%= link_to "Log in", login_path  %>
                </li>
              <% end %>
          </li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Georgi Mitrev 2013</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/users/_form.html.erb
<%= form_for @user, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :email, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :email, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :address, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :address, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                users_path, :class => 'btn' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/show.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%= @user.name %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @user.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:address) %>:</strong></dt>
  <dd><%= @user.address %></dd>
  <dt><strong><%= model_class.human_attribute_name(:rating) %>:</strong></dt>
  <dd><%= @user.rating.round(1) %></dd>
</dl>
<div class='row-fluid'>
  <div class='span6' style='padding: 10px; border: 1px solid #f1f1f1'>
    <h2>WANTS</h2>
      <% Book.all.each do |book| %>
        <a href="<%= book_path(book) %>" class="span2 user-book" style="text-align: center">
          <%= image_tag "/covers/#{book.isbn}.jpg", size: '71x107', class: "cover" %>
          <br />
            <%= book.title %>
        </a>
      <% end %>
  </div>
  <div class='span6' style='padding: 10px; border: 1px solid #f1f1f1'>
    <h2>OFFERS</h2>
  </div>
</div>

<div class="form-actions">
    <%= link_to t('.back', :default => t("helpers.links.back")),
              users_path, :class => 'btn'  %>
  <% if current_user == @user %>
    <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_user_path(@user), :class => 'btn' %>
  <% end  %>
  <% if admin? %>
    <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              user_path(@user),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
<% end %>
</div>